sand1 = love.graphics.newImage("assets/sand_1.png")
sand2 = love.graphics.newImage("assets/sand_2.png")
sand3 = love.graphics.newImage("assets/sand_3.png")
img_heart = love.graphics.newImage("assets/heart.png")
toxik_gaz = love.graphics.newImage("assets/toxik_gaz.png")
img_heart_empty = love.graphics.newImage("assets/heart_empty.png")
