sand1 = love.graphics.newImage("assets/sand_1.png")
sand2 = love.graphics.newImage("assets/sand_2.png")
sand3 = love.graphics.newImage("assets/sand_3.png")
img_heart = love.graphics.newImage("assets/heart.png")
toxic_gas = love.graphics.newImage("assets/toxic_gas.png")
img_heart_empty = love.graphics.newImage("assets/heart_empty.png")
logo = love.graphics.newImage("assets/logo.png")
